//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class excercises
    {
        public int id { get; set; }
        public Nullable<int> first_column { get; set; }
        public Nullable<int> second_column { get; set; }
        public Nullable<int> thrid_column { get; set; }
    }
}
